ALTER TABLE users ADD COLUMN role VARCHAR(20);

UPDATE users SET role = 'REQUESTER' WHERE role IS NULL;

ALTER TABLE users ADD CONSTRAINT ck_users_role CHECK (role IN ('REQUESTER', 'AGENT', 'ADMIN'));

ALTER TABLE users ALTER COLUMN role SET NOT NULL;
